# Generated by Django 4.2.1 on 2023-05-09 16:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product_brand_product_color_alter_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_value', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': "To'lov turui",
                'verbose_name_plural': "To'lov turi",
            },
        ),
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('name', models.CharField(max_length=150, verbose_name='foydalanuvchining ismi')),
                ('number', models.IntegerField(verbose_name='Foydalanuvchinig telefon raqami')),
                ('ovner', models.CharField(max_length=150, verbose_name='ishchi nomi')),
                ('client_reception_time', models.DateField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Foydalanuvchi yaratish',
                'verbose_name_plural': 'Foydalanuvchilarni yaratish',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='items_outprice',
            field=models.IntegerField(default=1, verbose_name='Sotilish narxi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='items_incash_value',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.cash', verbose_name="To'lov turi"),
            preserve_default=False,
        ),
    ]
