# Generated by Django 4.2.1 on 2023-05-10 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_userservice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userregister',
            old_name='name',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='userservice',
            old_name='name',
            new_name='username',
        ),
    ]
