# Generated by Django 4.2.1 on 2023-08-07 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skladik', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ishchilar',
            new_name='Worker',
        ),
    ]
