# Generated by Django 4.2.1 on 2023-08-07 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skladik', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='items_creator',
            field=models.CharField(default=1, max_length=50, verbose_name='Tovar krituvchi'),
            preserve_default=False,
        ),
    ]
