# Generated by Django 4.2.1 on 2023-08-22 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skladik', '0002_items_items_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endserviceclient',
            name='coment',
            field=models.CharField(max_length=150, verbose_name='koment'),
        ),
    ]
