# Generated by Django 4.2.1 on 2023-09-11 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skladik', '0003_alter_endserviceclient_coment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endserviceclient',
            old_name='coment',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='endserviceclient',
            old_name='produtct_not_repaired',
            new_name='product_not_repaired',
        ),
    ]
